'use strict';
const assert=require('node:assert/strict');
const O=require('../frontend/app/office3d.js');
const F=require('../frontend/app/productionflow.js');
const S=require('../frontend/app/shortspanel.js');
const now='2026-10-03T12:00:00.000Z';
const entry=data=>({data,loadedAt:now,error:null});
const base={ok:true,mode:'connected',connection:{configured:true},sources:[],jobs:[],clips:[],approvals:[],publications:[]};
const stage=(p,id)=>p.stages.find(s=>s.id===id);
const p=O.plan([{id:'hq',name:'HQ',kind:'hab'}],[{id:'real-agent',name:'Real'}],()=>null,{workflows:true});
assert.equal(p.length,3);assert.equal(p.flatMap(r=>r.agents).length,1);assert.equal(p[0].agents[0].id,'real-agent');
const arranged=O.layout(p);assert.deepEqual(arranged.slice(0,2).map(r=>r.workflow),['youtube','commerce']);
assert.ok(arranged.every(r=>r.y===0));
for(const a of arranged)for(const b of arranged)if(a.id!==b.id)assert.ok(Math.abs(a.x-b.x)>=(a.width+b.width)/2+12||Math.abs(a.z-b.z)>=(a.depth+b.depth)/2+12,'separated platforms');
const calls=[];const host={openAgent:id=>calls.push(['agent',id]),openTool:id=>calls.push(['tool',id]),openWorkflow:(k,s)=>calls.push([k,s])};
O.activate(host,{type:'agent',id:'real-agent'});O.activate(host,{type:'tool',id:'outbox'});O.activate(host,{type:'workflow',kind:'youtube',stage:'review'});
assert.deepEqual(calls,[['agent','real-agent'],['tool','outbox'],['youtube','review']]);
let view=F.project('youtube',entry({...base,connection:{configured:false}}),now);
assert.equal(stage(view,'processing').status,'review');assert.equal(stage(view,'processing').count,0);
view=F.project('youtube',entry({...base,sources:[{id:'a',title:'A'},{id:'b',title:'B',clearance:{}}]}),now);
assert.equal(stage(view,'permission').count,1);assert.equal(stage(view,'sources').count,1);
view=F.project('youtube',entry({...base,jobs:[{id:'j',sourceId:'a',state:'submission_unknown'}]}),now);
assert.equal(stage(view,'processing').status,'blocked');
view=F.project('youtube',entry({...base,jobs:[{id:'j',sourceId:'a',state:'processing'}]}),now);
assert.equal(stage(view,'processing').status,'working');
view=F.project('youtube',entry({...base,clips:[{id:'c',jobId:'j',available:true,title:'Clip'}],approvals:[{id:'a',clipId:'c',valid:true,publishAt:'2026-10-02T12:00:00.000Z'}],publications:[{id:'p',clipId:'c',approvalId:'a',state:'scheduled'}]}),now);
assert.equal(stage(view,'verify').status,'review');assert.equal(stage(view,'verify').count,1);assert.ok(!view.stages.some(s=>s.id==='published'));
const commerce={ok:true,mode:'demo',orders:[{id:'o',channelOrderId:'order',fulfillmentStatus:'processing',cancellationStatus:'none'}],exceptions:[],products:[]};
assert.equal(stage(F.project('commerce',entry(commerce),now),'production').status,'working');
assert.equal(stage(F.project('commerce',entry({...commerce,exceptions:[{orderId:'o',status:'open',summary:'Billing failed'}]}),now),'production').status,'blocked');
assert.ok(F.project('commerce',{...entry(commerce),error:'offline'},now).stages.every(s=>s.status==='unknown'));
assert.equal(stage(F.project('commerce',{data:null,error:'offline'},now),'orders').status,'unknown');
assert.equal(S.mediaUrl('javascript:alert(1)'),null);assert.equal(S.mediaUrl('https://secret@example.com/video'),null);
assert.ok(!S.renderSection('sources',{...base,sources:[{title:'<img src=x onerror=alert(1)>',creator:'<script>'}],capabilities:{}}).includes('<img'));
let n=0;const id=()=> 'fixture.'+(++n);
const approval=S.payload('clips/approve',{clipId:'c',fingerprint:'f',accountId:'yt',title:'title',description:'credit',publishAt:'2026-10-04T12:00:00Z',editorialNotes:'checked',rights:'on',originality:'on',captions:'on',framing:'on',audio:'on'},id);
assert.equal(approval.publishAt,'2026-10-04T12:00:00.000Z');assert.ok(Object.values(approval.checks).every(Boolean));assert.ok(!('rights' in approval));
assert.equal(S.payload('jobs/submit',{sourceId:'s',maxCredits:'25',confirmProcessing:'on'},id).maxCredits,25);
(async()=>{
  let fail=false;const store=F.create({now:()=>now,request:async()=>{if(fail)throw Error('offline');return commerce;}});
  await store.refresh('commerce');fail=true;await store.refresh('commerce');assert.equal(store.get('commerce').data.orders.length,1);assert.ok(store.project('commerce').stale);store.dispose();
  const resolvers=[];const race=F.create({now:()=>now,request:url=>new Promise(resolve=>resolvers.push({url,resolve}))});
  const old=race.refresh('commerce');race.setCommerceMode('demo');assert.equal(race.get('commerce').data,null);
  resolvers[0].resolve({...commerce,mode:'disconnected'});await old;await new Promise(r=>setImmediate(r));
  assert.equal(race.get('commerce').data,null);assert.equal(resolvers[1].url,'/api/commerce?mode=demo');resolvers[1].resolve(commerce);await new Promise(r=>setImmediate(r));assert.equal(race.get('commerce').data.mode,'demo');race.dispose();
  console.log('production-rooms.test: OK — layout, handlers, state truth, escaping, commands and stale/mode races');
})().catch(e=>{console.error(e);process.exitCode=1;});
